services:
  download:
    image: alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    command: ['/bin/sh', '/download.sh']
    volumes:
      - ./wwwroot:/wwwroot
      - ./download.sh:/download.sh:ro

  server:
    image: joseluisq/static-web-server:2@sha256:6acea6260b14e08dda986361e42640082fbfaab8d88c327de532bb13a3b22994
    depends_on:
      download:
        condition: service_completed_successfully
    environment:
      SERVER_ROOT: /public
      SERVER_CORS_ALLOW_ORIGINS: '*'
      SERVER_CORS_ALLOW_HEADERS: 'range, if-range, origin, content-type'
    volumes:
      - ./wwwroot:/public:ro
    ports:
      - '9205:80'
