services:
  download:
    image: alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
    command: ['/bin/sh', '/download.sh']
    volumes:
      - ./wwwroot:/wwwroot
      - ./download.sh:/download.sh:ro

  server:
    image: joseluisq/static-web-server:2@sha256:94618e3d17802265a21926217e6f9e7832b311b6fbf5933684001739fafed06a
    depends_on:
      download:
        condition: service_completed_successfully
    environment:
      SERVER_ROOT: /public
      SERVER_CORS_ALLOW_ORIGINS: '*'
      SERVER_CORS_ALLOW_HEADERS: 'range, if-range, origin, content-type'
    volumes:
      - ./wwwroot:/public:ro
    ports:
      - '9205:80'
