services:
  opencloud:
    image: ${OC_IMAGE:-opencloudeu/opencloud-rolling:latest}
    entrypoint: /bin/sh
    command: ['-c', 'opencloud init || true && opencloud server']
    environment:
      OC_URL: https://host.docker.internal:9200
      OC_INSECURE: true
      OC_LOG_LEVEL: error
      IDM_ADMIN_PASSWORD: admin
      PROXY_ENABLE_BASIC_AUTH: true
      PROXY_TLS: 'false'
      WEB_ASSET_APPS_PATH: /web/apps
      WEB_UI_CONFIG_FILE: /web/config.json
    labels:
      traefik.enable: true
      traefik.http.routers.opencloud.tls: true
      traefik.http.routers.opencloud.rule: Host(`host.docker.internal`) && PathPrefix(`/`)
      traefik.http.routers.opencloud.entrypoints: opencloud
      traefik.http.services.opencloud.loadbalancer.server.port: 9200
      traefik.http.routers.opencloud.middlewares: cors
    volumes:
      - opencloud-config:/etc/opencloud
      - ./dev/docker/opencloud.web.config.json:/web/config.json
      - ./dev/docker/opencloud.apps.yaml:/etc/opencloud/apps.yaml
      # apps
      - ./packages/web-app-cast/dist:/web/apps/cast
      - ./packages/web-app-draw-io/dist:/web/apps/draw-io
      - ./packages/web-app-external-sites/dist:/web/apps/external-sites
      - ./packages/web-app-importer/dist:/web/apps/importer
      - ./packages/web-app-json-viewer/dist:/web/apps/json-viewer
      - ./packages/web-app-progress-bars/dist:/web/apps/progress-bars
      - ./packages/web-app-unzip/dist:/web/apps/unzip
    depends_on:
      - traefik

  companion:
    image: transloadit/companion:5.5.2
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST:-host-gateway}
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      COMPANION_CLIENT_ORIGINS: 'true'
      COMPANION_ALLOW_LOCAL_URLS: 'true'
      COMPANION_DATADIR: /tmp/companion/
      COMPANION_DOMAIN: host.docker.internal:9200
      COMPANION_PROTOCOL: https
      COMPANION_PATH: /companion
      COMPANION_ONEDRIVE_KEY: '${COMPANION_ONEDRIVE_KEY}'
      COMPANION_ONEDRIVE_SECRET: '${COMPANION_ONEDRIVE_SECRET}'
      COMPANION_TUS_DEFERRED_UPLOAD_LENGTH: 'false'
    volumes:
      - uppy_companion_datadir:/tmp/companion/
    labels:
      traefik.enable: true
      traefik.http.routers.companion.tls: true
      traefik.http.routers.companion.rule: Host(`host.docker.internal`) && PathPrefix(`/companion`)
      traefik.http.routers.companion.entrypoints: opencloud
      traefik.http.services.companion.loadbalancer.server.port: 3020

  traefik:
    image: traefik:v3.3.6
    restart: unless-stopped
    entrypoint:
      [
        '/bin/sh',
        '-c',
        "[ -f /certificates/server.key ] && ./entrypoint.sh $$@ || (apk add openssl && openssl req -subj '/CN=opencloud.test' -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout /certificates/server.key -out /certificates/server.crt && chmod -R 777 /certificates && ./entrypoint.sh $$@)"
      ]
    command:
      - '--pilot.dashboard=false'
      - '--log.level=DEBUG'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.file.directory=/configs'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.opencloud.address=:9200'
      - '--entrypoints.opencloud-federated.address=:10200'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.middlewares=https_config@docker'
      - '--entrypoints.websecure.http.tls.options=default'
    labels:
      traefik.enable: true
      traefik.http.routers.http_catchall.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.http_catchall.entrypoints: web
      traefik.http.routers.http_catchall.middlewares: https_config
      traefik.http.middlewares.https_config.headers.sslRedirect: true
      traefik.http.middlewares.https_config.headers.stsSeconds: 63072000
      traefik.http.middlewares.https_config.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.cors.headers.accesscontrolallowmethods: '*'
      traefik.http.middlewares.cors.headers.accesscontrolallowheaders: '*'
      traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist: '*'
      traefik.http.middlewares.cors.headers.accesscontrolexposeheaders: '*'
      traefik.http.middlewares.cors.headers.accesscontrolmaxage: 100
      traefik.http.middlewares.cors.headers.addvaryheader: true
    ports:
      - '9200:9200'
    volumes:
      - './dev/docker/traefik/certificates:/certificates'
      - './dev/docker/traefik/configs:/configs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

volumes:
  opencloud-config:
  uppy_companion_datadir:
