prefer-workspace-packages: true
packages:
  - 'packages/*'
  - 'tests/*'

autoInstallPeers: true
sharedWorkspaceLockfile: true
minimumReleaseAge: 720

# public so they are picked up by IDEs
publicHoistPattern:
  - '*eslint*'

overrides:
  '@module-federation/vite': '1.16.8'

allowBuilds:
  '@parcel/watcher': true
