---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [pull_request, manual, tag]

variables:
  - &node_image 'woodpeckerci/plugin-node-pm:1.3.6@sha256:975bba1b807d2a54c62e424b6f0b2649bc30d47aaa0c09591e31e50e576f73e8'

steps:
  - name: check-types
    image: *node_image
    settings:
      run: check:types
