---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [pull_request, manual]

variables:
  - &node_image 'owncloudci/nodejs:22'
  - &oc_image 'opencloudeu/opencloud-rolling:latest'
  - &alpine_image 'owncloudci/alpine:latest'
  - &minio_mc_image 'minio/mc:RELEASE.2021-10-07T04-19-58Z'
  - &tika_image 'apache/tika:3.2.3.0'

services:
  - name: tika
    image: *tika_image

steps:
  - name: pnpm-install
    image: *node_image
    commands:
      - pnpm install
  - name: build-extensions
    image: *node_image
    commands:
      - pnpm build
      - mkdir -p /apps
      - for dir in packages/*/dist; do mv "$dir" "/apps/$(basename $(dirname "$dir") | sed 's/^web-app-//')"; done
      - cp -R /apps /woodpecker/apps
  - name: wait-for-tika
    image: *alpine_image
    commands:
      - "timeout 60 bash -c 'until nc -z tika 9998; do sleep 1; done'"
  - name: opencloud
    image: *oc_image
    detach: true
    environment:
      OC_URL: https://opencloud:9200
      OC_INSECURE: true
      OC_LOG_LEVEL: error
      IDM_ADMIN_PASSWORD: admin
      PROXY_ENABLE_BASIC_AUTH: True
      WEB_ASSET_APPS_PATH: /woodpecker/apps
      WEB_UI_CONFIG_FILE: /var/lib/opencloud/web.config.json
      # Tika configuration
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: true
      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      SEARCH_EXTRACTOR_CS3SOURCE_INSECURE: true
    commands:
      - cp dev/docker/opencloud.apps.yaml /etc/opencloud/apps.yaml
      - cp dev/woodpecker/opencloud.web.config.json /var/lib/opencloud/web.config.json
      - opencloud init || true && opencloud server
  - name: wait-for-opencloud
    image: *alpine_image
    commands:
      - "timeout 200 bash -c 'while [ $(curl -sk -uadmin:admin https://opencloud:9200/graph/v1.0/users/admin -w %{http_code} -o /dev/null) != 200 ]; do sleep 1; done'"
  - name: install-browser
    image: *node_image
    commands:
      - pnpm exec playwright install chromium
      - cp -R /root/.cache/ms-playwright /woodpecker/playwright-cache

  - name: e2e-tests
    image: *node_image
    commands:
      - mkdir -p /root/.cache
      - cp -R /woodpecker/playwright-cache /root/.cache/ms-playwright
      - "BASE_URL_OC=https://opencloud:9200 pnpm test:e2e --project='*-chromium'"

  - name: upload-tracing-result
    image: *minio_mc_image
    environment:
      MC_HOST: 'https://s3.ci.opencloud.eu'
      AWS_ACCESS_KEY_ID:
        from_secret: cache_s3_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_s3_secret_key
      PUBLIC_BUCKET: 'public'
    commands:
      - 'mc alias set s3 $MC_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY'
      - 'mc cp -a -r test-results/ s3/$PUBLIC_BUCKET/web-extensions/tracing/$CI_PIPELINE_NUMBER/'
      - echo "========================================="
      - echo "Trace files uploaded successfully!"
      - echo "========================================="
      - echo "To view the traces, run the following commands:"
      - echo ""
      - |
        for f in test-results/*/*.zip; do
          if [ -f "$f" ]; then
            path=$(echo "$f" | sed 's|^test-results/||')
            echo "npx playwright show-trace $MC_HOST/$PUBLIC_BUCKET/web-extensions/tracing/$CI_PIPELINE_NUMBER/$path"
            echo ""
          fi
        done
      - echo "========================================="
    when:
      status: [failure]
