---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [pull_request, manual, tag]

variables:
  - &node_image 'woodpeckerci/plugin-node-pm:1.3.10@sha256:24674eb3d45f3027d39499e34630ab36a0d26aabc4f83688b1de150ba37646dc'

steps:
  - name: format
    image: *node_image
    settings:
      run: format:check
