---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [pull_request, manual, tag]

variables:
  - &node_image 'woodpeckerci/plugin-node-pm:1.3.6'

steps:
  - name: lint
    image: *node_image
    settings:
      run: lint
