---
when:
  - event: [tag]

variables:
  - &node_image 'quay.io/opencloudeu/nodejs-ci:24@sha256:efb3ac3e7e7180aa24fec6f6811d7a59385798676a6a7081dc092faa0800951b'
  - &alpine_image 'quay.io/opencloudeu/nodejs-alpine-ci:24@sha256:e336ffb29650e09ed07cbc6c94de18da6e83a1777e4fa28252729124775f1c48'
  - &release_image 'woodpeckerci/plugin-release:0.2.6@sha256:4a1eb273b61b162345d875d52ef1d788f69b2d829820a715d9c67b3e19e32387'
  - &docker_image 'woodpeckerci/plugin-docker-buildx:6.0.4@sha256:765ebfaa6f71383197babb2352c7902bafe141e6232a62cafb740510a788c550'
  - &extract_app_and_version
    - APP=${CI_COMMIT_TAG%-v*}
    - VERSION=${CI_COMMIT_TAG##*-v}

steps:
  - name: pnpm-install
    image: *node_image
    commands:
      - pnpm install

  - name: build
    image: *node_image
    commands:
      - <<: *extract_app_and_version
      - pnpm build
      - mkdir apps
      - cd "packages/web-app-$APP"
      - mv dist ../../apps/$APP

  - name: prepare-release
    image: *alpine_image
    commands:
      - <<: *extract_app_and_version
      # create zip archive
      - cd apps
      - apk add zip
      - zip -r $APP-$VERSION.zip $APP/

      # determine if prerelease
      - echo "${CI_COMMIT_TAG}" | grep -q '\-alpha\.\|\-beta\.\|\-rc\.' && export PLUGIN_PRERELEASE=true || export PLUGIN_PRERELEASE=false
      - mkdir -p /woodpecker/github
      - echo "PLUGIN_PRERELEASE=$PLUGIN_PRERELEASE" >> /woodpecker/github/.env

      # export docker build args for publish-docker step
      - mkdir -p /woodpecker/docker
      - echo "APP_PATH=./apps/$APP" >> /woodpecker/docker/.env
      - echo "APP_NAME=$APP" >> /woodpecker/docker/.env

  - name: publish-github
    image: *release_image
    settings:
      api_key:
        from_secret: github_token
      title: ${CI_COMMIT_TAG%-v*} ${CI_COMMIT_TAG##*-v}
      overwrite: true
      env_file: /woodpecker/github/.env
      files:
        - apps/*.zip
      checksum:
        - md5
        - sha256
  - name: publish-docker
    image: *docker_image
    settings:
      dockerfile: docker/Dockerfile
      repo: opencloudeu/web-extensions,quay.io/opencloudeu/web-extensions
      platforms: linux/amd64,linux/arm64
      tags:
        - ${CI_COMMIT_TAG%-v*}-${CI_COMMIT_TAG##*-v}
        - ${CI_COMMIT_TAG%-v*}-latest
      build_args_from_env:
        - APP_PATH
        - APP_NAME
      env_file: /woodpecker/docker/.env
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://quay.io
          username:
            from_secret: quay_username
          password:
            from_secret: quay_password
    when:
      - evaluate: 'not (CI_COMMIT_TAG contains "-alpha." || CI_COMMIT_TAG contains "-beta." || CI_COMMIT_TAG contains "-rc.")'
