---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [pull_request, manual, tag]

variables:
  - &node_image 'woodpeckerci/plugin-node-pm:latest'

steps:
  - name: unit-tests
    image: *node_image
    settings:
      run: test:unit
